global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "gateway"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["gateway:8000"]
        labels:
          service: "gateway"

  - job_name: "ml-worker"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["ml-worker:8001"]
        labels:
          service: "ml-worker"
